<?php

/*
 *   Project : Project name
 * 
 *   Author  : Sandeep Giri
 * 
 *   Contact : ioesandeep@gmail.com
 * 
 *   File    : business.php
 * 
 *   Project : saffersmall
 */

/*
 *   <Saffersmall :: Online Ads and Marketing Directory.>
 *   Copyright (C) <2014>  <Sandeep Giri>

 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.

 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.

 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 *   This program comes with ABSOLUTELY NO WARRANTY.
 *   This is free software, and you are welcome to redistribute it only if you 
 *   get permissions from the author or the distributor of this code.
 * 
 *   However do not expect any help or support from the author.
 */
?>
<html>
    <body>
        <h4>Dear <?php echo $data['registrar'];?>,</h4>
        <p style="text-indent: 50px">Thank you for choosing <a href="//saffersmall.com">saffersmall.com</a>. We have sent you this email to confirm you have been successfully registered on <a href="//saffersmall.com">saffersmall.com</a>. Below is the credentials required to activate you account.</p>
        <p></p>
        <p>
            Enter the following pin number in the account activation form.
            <br/>
            <?php echo $data['pin'];?>
        </p>
        <p>or,</p>
        <p>Click on the following link to directly activate your account from here.</p>
        <p><a href="//saffersmall.com/account/activate/<?php echo $data['token'];?>">Activate your account.</a></p>
        <p></p>
        <p>The following credentials have been recorded for this email.</p>
        <table>
            <tr>
                <th>Business Owner</th>
                <th><?php echo $data['registrar'];?></th>
            </tr>
            <tr>
                <th>Business name</th>
                <th><?php echo $data['business'];?></th>
            </tr>
            <tr>
                <th>Username</th>
                <th><?php echo $data['username'];?></th>
            </tr>
            <tr>
                <th>Phone</th>
                <th><?php echo $data['phone'];?></th>
            </tr>
        </table>
        <p></p>
        <p></p>
        <h4>This is an automated email generated by <a href="//saffersmall.com">saffersmall.com</a> mail engine. Please do not reply to email. You may not receive any response further.</h4>
    </body>
</html>
